name: proj_230
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - geopandas
  - shapely
  - scipy
  - scikit-learn
  - statsmodels
  - requests
  - pip
  - openpyxl
  - pyyaml
  - statsmodels
  - seaborn